;;;; ============================================================
;;;; emitter: builtins: taf-app.lisp
;;;; ============================================================

(defpackage :taffish.emitter.builtins.taf-app
  (:use :cl)
  (:export
   :match-taf-app-tag
   :emit-taf-app
   :finalize-taf-app))

(in-package :taffish.emitter.builtins.taf-app)

;;;; ============================================================
;;;; helper emitter
;;;; ============================================================

(defun %clean-string (string &key (trim-fun #'string-trim))
  (funcall trim-fun '(#\Space #\Tab) string))

(defun %string-prefix-p (prefix string &key (test #'char-equal))
  (labels ((spp (i)
             (let ((p-i (ignore-errors (char prefix i)))
                   (s-i (ignore-errors (char string i))))
               (cond
                 ((null p-i) t)
                 ((null s-i) nil)
                 ((funcall test p-i s-i) (spp (1+ i)))
                 (t nil)))))
    (spp 0)))

;;;; ============================================================
;;;; match emitter
;;;; ============================================================

(defun %parse-taf-app-tag (raw-tag)
  (let ((clean-tag (%clean-string raw-tag :trim-fun #'string-left-trim)))
    (if (%string-prefix-p "taf-app:" clean-tag :test #'char-equal)
        (values (subseq clean-tag (length "taf-app:")) t)
        (values clean-tag nil))))

;; <taf-app:...>
(defun match-taf-app-tag (raw-tag line-number)
  (multiple-value-bind (tag taf-app-p)
      (%parse-taf-app-tag raw-tag)
    (when taf-app-p
      (list :kind :taf-app
            :tag raw-tag
            :line-number line-number
            :next-tag tag))))

;;;; ============================================================
;;;; emit emitter
;;;; ============================================================

(defun %argv-command-p (first-arg-string)
  (and (stringp first-arg-string)
       (let ((first-arg (%clean-string first-arg-string)))
         (and first-arg (stringp first-arg)
              (not (string= "" first-arg))
              (not (char= #\- (char first-arg 0)))))))

(defun emit-taf-app (parsed-info lines taf-result)
  (let* ((next-tag (getf parsed-info :next-tag))
         (context (taffish.core:taf-result-context taf-result))
         (argv-list (and context
                         (taffish.core:taf-context-argv context)))
         (argv-string (format nil "~{~A~^ ~}" argv-list)))
    (list
     (if (%argv-command-p (car argv-list))
         (let ((next-lines (list (list :line argv-string :number 0))))
           (taffish.core:emit-block next-tag next-lines taf-result))
         (taffish.core:emit-block next-tag lines taf-result)))))

(defun finalize-taf-app (parsed-info shell-lines-list taf-result)
  (declare (ignore parsed-info taf-result))
  (if (and (listp shell-lines-list)
           (= (length shell-lines-list) 2)
           (stringp (car shell-lines-list))
           (stringp (second shell-lines-list)))
      (format nil "~{~A~^~%~}" shell-lines-list)
      (error "TAF-APP finalize expects one prelude line and one shell string, but got: ~S"
             shell-lines-list)))

;;;; ============================================================
;;;; emitter: builtins: taf-app.lisp
;;;; ============================================================

(in-package :taffish.core)

(defemitter taf-app
  :match-function #'taffish.emitter.builtins.taf-app:match-taf-app-tag
  :emit-function #'taffish.emitter.builtins.taf-app:emit-taf-app
  :prelude-function #'(lambda (parsed-info lines taf-result)
                        (declare (ignore parsed-info lines taf-result))
                        (list "### Generated by TAFFISH: TAF-APP"))
  :finalize-function #'taffish.emitter.builtins.taf-app:finalize-taf-app)
