(in-package :taffish.core)

;;;; ============================================================
;;;; emitter: registry.lisp
;;;; ============================================================

;; resolved-line: (:line <line-string> :number <line-number>)
(defun %get-line-number (line)
  (and line (getf line :number)))

;; resolved-line: (:line <line-string> :number <line-number>)
(defun %get-line-string (line)
  (and line (getf line :line)))

(defun %last1 (list)
  (car (last list)))

;; parsed-info: (:kind <emitter-name> :tag <tag-string> ...)
(defun default-prelude (parsed-info lines taf-result)
  (let ((tag (getf parsed-info :tag))
        (args-result (taf-result-args-result taf-result)))
    (list "### Generated by TAFFISH"
          (format nil "# TAG: <~A>" tag)
          (format nil "# SOURCE LINES: ~A - ~A"
                  (%get-line-number (car lines))
                  (%get-line-number (%last1 lines)))
          (format nil "# LOADDIR: ~A"
                  (han.args:get-arg "*LOADDIR*" args-result))
          (format nil "# WORKDIR: ~A"
                  (han.args:get-arg "*WORKDIR*" args-result)))))

(defun default-finalize (parsed-info shell-lines-list taf-result)
  (declare (ignore parsed-info taf-result))
  (format nil "~{~A~^~%~}" shell-lines-list))

(defun %string-list-p (x)
  (and (listp x)
       (every #'stringp x)))

(defun %find-emitter-by-name (name &optional (emitters *taf-emitters*))
  (find name emitters
        :key #'taf-emitter-name
        :test #'string-equal))

(defun register-emitter (emitter)
  (unless (taf-emitter-p emitter)
    (error "Emitter must be TAF-EMITTER, but got: ~S"
           (type-of emitter)))
  (when (%find-emitter-by-name (taf-emitter-name emitter))
    (error "Emitter name already registered: ~A"
           (taf-emitter-name emitter)))
  (setf *taf-emitters*
        (nconc *taf-emitters* (list emitter)))
  emitter)

(defmacro defemitter (name &key match-function
                             emit-function
                             prelude-function
                             finalize-function)
  `(register-emitter
    (make-taf-emitter
     :name ,(string-downcase (string name))
     :match-function ,match-function
     :emit-function ,emit-function
     :prelude-function ,prelude-function
     :finalize-function ,finalize-function)))

(defun %block-tag-line-number (lines)
  (let ((n (%get-line-number (car lines))))
    (when (and (integerp n)
               (> n 0))
      (1- n))))

;; resolved-line: (:line <line-string> :number <line-number>)
(defun emit-block (tag lines taf-result &optional (emitters *taf-emitters*))
  (dolist (emitter emitters)
    (let ((match-fun (taf-emitter-match-function emitter)))
      (unless match-fun
        (error "Emitter ~A has no MATCH-FUNCTION."
               (taf-emitter-name emitter)))
      (let ((parsed-info (funcall match-fun tag
                                  (%block-tag-line-number lines))))
        (when parsed-info
          (let ((prelude-fun (or (taf-emitter-prelude-function emitter)
                                 #'default-prelude))
                (emit-fun (taf-emitter-emit-function emitter))
                (finalize-fun (or (taf-emitter-finalize-function emitter)
                                  #'default-finalize)))
            (unless emit-fun
              (error "Emitter ~A has no EMIT-FUNCTION."
                     (taf-emitter-name emitter)))
            (let ((prelude-list
                    (funcall prelude-fun parsed-info lines taf-result))
                  (shell-list
                    (funcall emit-fun parsed-info lines taf-result)))
              (unless (%string-list-p prelude-list)
                (error "PRELUDE-FUNCTION must return shell-list, but got: ~S"
                       (type-of prelude-list)))
              (unless (%string-list-p shell-list)
                (error "EMIT-FUNCTION must return shell-list, but got: ~S"
                       (type-of shell-list)))
              (let* ((all-shell-list (append prelude-list shell-list))
                     (shell-string (funcall finalize-fun
                                            parsed-info
                                            all-shell-list
                                            taf-result)))
                (if (stringp shell-string)
                    (return-from emit-block shell-string)
                    (error "FINALIZE-FUNCTION must return shell-string, but got: ~S"
                           (type-of shell-string))))))))))
  (error "No emitter matched tag: ~A" tag))
