# fish completion for taf

complete -c taf -f

complete -c taf -n "__fish_use_subcommand" -a "new" -d "Create a new TAFFISH app project"
complete -c taf -n "__fish_use_subcommand" -a "check" -d "Check current TAFFISH app project"
complete -c taf -n "__fish_use_subcommand" -a "compile" -d "Compile current project and print shell code"
complete -c taf -n "__fish_use_subcommand" -a "build" -d "Build current project into taf-command"
complete -c taf -n "__fish_use_subcommand" -a "run" -d "Compile and run current project"
complete -c taf -n "__fish_use_subcommand" -a "publish" -d "Publish current project to GitHub"
complete -c taf -n "__fish_use_subcommand" -a "update" -d "Update local TAFFISH index"
complete -c taf -n "__fish_use_subcommand" -a "search" -d "Search apps from local index"
complete -c taf -n "__fish_use_subcommand" -a "info" -d "Show app information"
complete -c taf -n "__fish_use_subcommand" -a "install" -d "Install apps from TAFFISH-HUB"
complete -c taf -n "__fish_use_subcommand" -a "uninstall" -d "Uninstall local apps"
complete -c taf -n "__fish_use_subcommand" -a "list" -d "List installed or indexed apps"
complete -c taf -n "__fish_use_subcommand" -a "which" -d "Show paths and metadata"
complete -c taf -n "__fish_use_subcommand" -a "doctor" -d "Check or initialize TAFFISH environment"
complete -c taf -n "__fish_use_subcommand" -a "config" -d "Show TAFFISH config"
complete -c taf -n "__fish_use_subcommand" -a "history" -d "Show or clear local run history"
complete -c taf -n "__fish_use_subcommand" -a "help" -d "Show help"
complete -c taf -n "__fish_use_subcommand" -a "version" -d "Show version"

complete -c taf -s h -l help -d "Show help"
complete -c taf -s v -l version -d "Show version"

complete -c taf -n "__fish_seen_subcommand_from new" -s t -l tool -d "Create a tool project"
complete -c taf -n "__fish_seen_subcommand_from new" -s f -l flow -d "Create a flow project"
complete -c taf -n "__fish_seen_subcommand_from new" -s v -l version -r -d "Set version"
complete -c taf -n "__fish_seen_subcommand_from new" -s r -l release -r -d "Set release"
complete -c taf -n "__fish_seen_subcommand_from new" -s l -l license -xa "Apache-2.0 MIT BSD-2-Clause BSD-3-Clause GPL-3.0 LGPL-3.0 AGPL-3.0 Unlicense" -d "Set license"
complete -c taf -n "__fish_seen_subcommand_from new" -s g -l repo -r -d "Set GitHub repository URL"
complete -c taf -n "__fish_seen_subcommand_from new" -s i -l image -r -d "Set container image"
complete -c taf -n "__fish_seen_subcommand_from new" -s d -l docker -d "Create Dockerfile and workflow"
complete -c taf -n "__fish_seen_subcommand_from new" -l no-actions -d "Do not create GitHub Actions workflow"

complete -c taf -n "__fish_seen_subcommand_from compile" -a "--" -d "Pass following args to app"
complete -c taf -n "__fish_seen_subcommand_from build" -s i -l image -d "Build container image only"
complete -c taf -n "__fish_seen_subcommand_from build" -s d -l docker -d "Build container image only"
complete -c taf -n "__fish_seen_subcommand_from build" -s a -l all -d "Build command and image"
complete -c taf -n "__fish_seen_subcommand_from build" -s b -l backend -xa "docker podman" -d "Select image backend"
complete -c taf -n "__fish_seen_subcommand_from run" -s b -l backend -xa "docker podman apptainer" -d "Force container backend"
complete -c taf -n "__fish_seen_subcommand_from run" -a "--" -d "Pass following args to app"

complete -c taf -n "__fish_seen_subcommand_from publish" -s n -l dry-run -d "Print publish plan only"
complete -c taf -n "__fish_seen_subcommand_from publish" -s y -l yes -d "Commit, tag, push and release"
complete -c taf -n "__fish_seen_subcommand_from publish" -s b -l build -d "Build before publishing"
complete -c taf -n "__fish_seen_subcommand_from publish" -s r -l release -d "Read release.md and create GitHub release"
complete -c taf -n "__fish_seen_subcommand_from publish" -l latest -d "Require newer than remote latest"
complete -c taf -n "__fish_seen_subcommand_from publish" -l pre -d "Allow non-latest prerelease"
complete -c taf -n "__fish_seen_subcommand_from publish" -l create-repo -d "Create GitHub repository if missing"
complete -c taf -n "__fish_seen_subcommand_from publish" -l public -d "Create repository as public"
complete -c taf -n "__fish_seen_subcommand_from publish" -l private -d "Create repository as private"
complete -c taf -n "__fish_seen_subcommand_from publish" -l no-lock-repo -d "Do not lock a newly created repository"
complete -c taf -n "__fish_seen_subcommand_from publish" -l prompt -d "Allow git credential prompts"

complete -c taf -n "__fish_seen_subcommand_from update search info install uninstall list which doctor" -s u -l user -d "Use user scope"
complete -c taf -n "__fish_seen_subcommand_from update search info install uninstall list which doctor" -s s -l system -d "Use system scope"
complete -c taf -n "__fish_seen_subcommand_from update" -l url -r -d "Index URL or local index file"
complete -c taf -n "__fish_seen_subcommand_from update" -s y -l yes -d "Non-interactive compatibility"
complete -c taf -n "__fish_seen_subcommand_from search info list which history" -s j -l json -d "Print JSON"
complete -c taf -n "__fish_seen_subcommand_from search" -s l -l limit -r -d "Limit result count"
complete -c taf -n "__fish_seen_subcommand_from list" -s n -l limit -r -d "Limit result count"
complete -c taf -n "__fish_seen_subcommand_from install" -s n -l dry-run -d "Print install plan only"
complete -c taf -n "__fish_seen_subcommand_from install" -s f -l force -d "Replace existing installation"
complete -c taf -n "__fish_seen_subcommand_from install" -l from -r -d "Install from local TAFFISH project directory"
complete -c taf -n "__fish_seen_subcommand_from install" -l prompt -d "Allow git credential prompts"
complete -c taf -n "__fish_seen_subcommand_from list" -s l -l local -d "List local installations"
complete -c taf -n "__fish_seen_subcommand_from list" -l installed -d "List local installations"
complete -c taf -n "__fish_seen_subcommand_from list" -s o -l online -d "List indexed apps"
complete -c taf -n "__fish_seen_subcommand_from list" -l index -d "List indexed apps"
complete -c taf -n "__fish_seen_subcommand_from uninstall" -s n -l dry-run -d "Print uninstall plan only"
complete -c taf -n "__fish_seen_subcommand_from uninstall" -s f -l force -d "Do not fail when missing"
complete -c taf -n "__fish_seen_subcommand_from doctor" -s i -l init -d "Create missing TAFFISH home directories"
complete -c taf -n "__fish_seen_subcommand_from config" -a "show path init" -d "Config action"
complete -c taf -n "__fish_seen_subcommand_from config" -s u -l user -d "Use user scope"
complete -c taf -n "__fish_seen_subcommand_from config" -s s -l system -d "Use system scope"
complete -c taf -n "__fish_seen_subcommand_from config" -l github -d "Initialize GitHub/default profile"
complete -c taf -n "__fish_seen_subcommand_from config" -l china -d "Initialize China mirror profile template"
complete -c taf -n "__fish_seen_subcommand_from config" -s f -l force -d "Replace existing config during init"
complete -c taf -n "__fish_seen_subcommand_from history" -s l -l last -r -d "Show last N events"
complete -c taf -n "__fish_seen_subcommand_from history" -s i -l id -r -d "Show one event by id"
complete -c taf -n "__fish_seen_subcommand_from history" -s p -l path -d "Print history file path"
complete -c taf -n "__fish_seen_subcommand_from history" -s c -l clear -d "Clear history file"
