(han:load-relative "package.lisp")
(han:load-relative "model.lisp")
(han:load-relative "lexer.lisp")
(han:load-relative "parser.lisp")
(han:load-relative "input.lisp")
(han:load-relative "binder.lisp")
(han:load-relative "emitter" "model.lisp")
(han:load-relative "emitter" "registry.lisp")
;;(han:load-relative "emitter" "builtins.lisp")
;;(han:load-relative "compiler.lisp")
;;(han:load-relative "main.lisp")
